"""Search for low-degree exact stationary identities for the spine share.

If a quadratic h and constant c obey

    s(x) - c = h(x) - E_z[h(K_z x / ||K_z x||)]

pointwise, then every stationary measure has E[s] = c.  This script searches
the complete 136-dimensional space of quadratic forms h, first with
c = 1/8 + 1/147 fixed and then with c free.  A genuine identity would have
machine-zero residual on fresh states.

The script first searches all quadratic forms. It then searches the complete
G2-invariant polynomial basis through degree six. Since P and s are
G2-invariant, any polynomial solution can be averaged over G2, so the invariant
search loses no polynomial solution.

This is a falsification check for low-degree analytic proofs, not a proof that
the proposed constant is wrong and not a search over rational coboundaries.
"""

import itertools

import numpy as np


def main() -> None:
    data = np.load("data/kraus84.npz")
    kraus = data["K"]
    event_count, dim, _ = kraus.shape
    eye = np.eye(dim)
    e0 = eye[0]

    channel = sum(np.kron(k.T, k.T) for k in kraus) / event_count
    eigenvalues, eigenvectors = np.linalg.eigh(channel)
    clock = eigenvectors[:, np.argmin(abs(eigenvalues + 1))].reshape(dim, dim)
    clock *= np.sqrt(dim) / np.linalg.norm(clock)
    e8 = clock @ e0
    spine = np.outer(e0, e0) + np.outer(e8, e8)
    upper = np.triu_indices(dim)

    def quadratic_coordinates(matrix: np.ndarray) -> np.ndarray:
        coordinates = matrix[upper].copy()
        coordinates[upper[0] != upper[1]] *= 2
        return coordinates

    def coboundary_row(x: np.ndarray) -> np.ndarray:
        images = np.einsum("aij,j->ai", kraus, x)
        norms = np.linalg.norm(images, axis=1)
        images = images[norms > 1e-12] / norms[norms > 1e-12, None]
        next_second_moment = np.einsum("ai,aj->ij", images, images) / len(images)
        return quadratic_coordinates(np.outer(x, x) - next_second_moment)

    rng = np.random.default_rng(20260730)
    candidate = 1 / 8 + 1 / 147

    def sample(count: int) -> tuple[np.ndarray, np.ndarray]:
        states = rng.normal(size=(count, dim))
        states /= np.linalg.norm(states, axis=1, keepdims=True)
        rows = np.array([coboundary_row(x) for x in states])
        shares = np.einsum("ai,ij,aj->a", states, spine, states)
        return rows, shares

    train_rows, train_shares = sample(1200)
    test_rows, test_shares = sample(400)

    fixed_coefficients = np.linalg.lstsq(
        train_rows, train_shares - candidate, rcond=1e-12
    )[0]
    fixed_residual = (
        test_rows @ fixed_coefficients - (test_shares - candidate)
    )

    augmented = np.column_stack([np.ones(len(train_rows)), train_rows])
    free_solution = np.linalg.lstsq(augmented, train_shares, rcond=1e-12)[0]
    free_residual = (
        np.column_stack([np.ones(len(test_rows)), test_rows]) @ free_solution
        - test_shares
    )

    print(f"quadratic coboundary rank: {np.linalg.matrix_rank(train_rows)}/136")
    print(f"candidate c: {candidate:.15f}")
    print(
        "fixed-candidate test residual: "
        f"rms={np.sqrt(np.mean(fixed_residual**2)):.3e}, "
        f"max={np.max(abs(fixed_residual)):.3e}"
    )
    print(f"best free constant: {free_solution[0]:.15f}")
    print(
        "free-constant test residual: "
        f"rms={np.sqrt(np.mean(free_residual**2)):.3e}, "
        f"max={np.max(abs(free_residual)):.3e}"
    )

    # An exact quadratic identity would reproduce at floating-point noise.
    if np.sqrt(np.mean(fixed_residual**2)) < 1e-10:
        raise SystemExit("unexpected exact quadratic identity found")

    # G2 fixes the two scalar axes and acts diagonally on two copies of R7.
    # On two 7-vectors its scalar invariants are generated by their Gram
    # entries, so a, b, |u|^2, |v|^2, and u.v generate the invariant ring.
    exponents = []
    for powers in itertools.product(range(7), repeat=5):
        weighted_degree = powers[0] + powers[1] + 2 * sum(powers[2:])
        if 1 <= weighted_degree <= 6:
            exponents.append(powers)

    def invariant_features(x: np.ndarray) -> np.ndarray:
        a, b = x @ e0, x @ e8
        u, v = x[1:8], x[9:16]
        generators = (a, b, u @ u, v @ v, u @ v)
        return np.array(
            [
                np.prod([generators[i] ** power for i, power in enumerate(powers)])
                for powers in exponents
            ]
        )

    def transferred_invariant_features(x: np.ndarray) -> np.ndarray:
        images = np.einsum("aij,j->ai", kraus, x)
        norms = np.linalg.norm(images, axis=1)
        images = images[norms > 1e-12] / norms[norms > 1e-12, None]
        return np.mean([invariant_features(image) for image in images], axis=0)

    def invariant_sample(count: int) -> tuple[np.ndarray, np.ndarray]:
        states = rng.normal(size=(count, dim))
        states /= np.linalg.norm(states, axis=1, keepdims=True)
        rows = np.array(
            [
                invariant_features(x) - transferred_invariant_features(x)
                for x in states
            ]
        )
        shares = np.einsum("ai,ij,aj->a", states, spine, states)
        return rows, shares

    degree6_rows, degree6_shares = invariant_sample(900)
    degree6_test_rows, degree6_test_shares = invariant_sample(300)
    degree6_coefficients = np.linalg.lstsq(
        degree6_rows, degree6_shares - candidate, rcond=1e-12
    )[0]
    degree6_residual = (
        degree6_test_rows @ degree6_coefficients
        - (degree6_test_shares - candidate)
    )
    degree6_rms = np.sqrt(np.mean(degree6_residual**2))

    print(
        f"degree-6 G2-invariant rank: "
        f"{np.linalg.matrix_rank(degree6_rows)}/{len(exponents)}"
    )
    print(
        "degree-6 fixed-candidate test residual: "
        f"rms={degree6_rms:.3e}, "
        f"max={np.max(abs(degree6_residual)):.3e}"
    )
    if degree6_rms < 1e-10:
        raise SystemExit("unexpected exact degree-6 identity found")

    print(
        "RESULT: no polynomial stationary coboundary through degree six proves "
        "s* = 1/8 + 1/147; rational/non-polynomial analysis remains open."
    )


if __name__ == "__main__":
    main()
